# Change these first
owner: abusayed0206 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Intro
    url: https://sayed.page
  - name: Resume
    url: https://abusayed.dev
  - name: Blog
    url: https://blog.abusayed.dev/
  - name: Projects
    url: https://sayed.app
  - name: Laws of Bangladesh
    url: https://laws.sayed.app
  - name: CUET Student Directory
    url: https://cuet.sayed.app
  - name: Bangla Movies & TV Series
    url: https://movies.sayed.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sayed.app
  # baseUrl: /your-repo-name
  logoUrl: https://commons.wikimedia.org/wiki/File:Flag_of_Bangladesh.svg
  name: Status Page
  introTitle: "This site is powered by Upptime"
  introMessage: I listed my personal sites here to keep track of their uptime and performance. Upptime is an open-source GitHub Action that turns your repository into a status page, powered by GitHub Actions and Issues.
  navbar:
    - title: Projects
      href: https://sayed.app

  theme: night
