# Change these first
owner: abusayed0206 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: AbuSayed.dev
    url: https://abusayed.dev
  - name: AbuSayed.dev Blog
    url: https://blog.abusayed.dev
  - name: Sayed.Page 
    url: https://sayed.page/
  - name: About Sayed.Page
    url: https://about.sayed.page/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: monitor.sayed.page
  # baseUrl: /your-repo-name
  logoUrl: https://abusayed.dev/apple-touch-icon.png
  name: Monitor
  introTitle: "This website is for monitoring personal sites purpose"
  introMessage: This site is powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: https://sayed.page
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
